// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: pwd.proto

package pwd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PWD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Url     string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	Account string `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	Pwd     string `protobuf:"bytes,5,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Remark  string `protobuf:"bytes,6,opt,name=Remark,proto3" json:"Remark,omitempty"`
}

func (x *PWD) Reset() {
	*x = PWD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PWD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PWD) ProtoMessage() {}

func (x *PWD) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PWD.ProtoReflect.Descriptor instead.
func (*PWD) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{0}
}

func (x *PWD) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PWD) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PWD) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PWD) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PWD) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *PWD) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreatePwdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Url     string `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	Account string `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	Pwd     string `protobuf:"bytes,4,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Remark  string `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`
}

func (x *CreatePwdReq) Reset() {
	*x = CreatePwdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePwdReq) ProtoMessage() {}

func (x *CreatePwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePwdReq.ProtoReflect.Descriptor instead.
func (*CreatePwdReq) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePwdReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePwdReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreatePwdReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreatePwdReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *CreatePwdReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreatePwdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreatePwdResp) Reset() {
	*x = CreatePwdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePwdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePwdResp) ProtoMessage() {}

func (x *CreatePwdResp) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePwdResp.ProtoReflect.Descriptor instead.
func (*CreatePwdResp) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePwdResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePwdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdatePwdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Url     string `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	Account string `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	Pwd     string `protobuf:"bytes,4,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Remark  string `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`
}

func (x *UpdatePwdReq) Reset() {
	*x = UpdatePwdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePwdReq) ProtoMessage() {}

func (x *UpdatePwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePwdReq.ProtoReflect.Descriptor instead.
func (*UpdatePwdReq) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePwdReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePwdReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdatePwdReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UpdatePwdReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *UpdatePwdReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdatePwdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *UpdatePwdResp) Reset() {
	*x = UpdatePwdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePwdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePwdResp) ProtoMessage() {}

func (x *UpdatePwdResp) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePwdResp.ProtoReflect.Descriptor instead.
func (*UpdatePwdResp) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePwdResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePwdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetPwdListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum  int64 `protobuf:"varint,1,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *GetPwdListReq) Reset() {
	*x = GetPwdListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPwdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPwdListReq) ProtoMessage() {}

func (x *GetPwdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPwdListReq.ProtoReflect.Descriptor instead.
func (*GetPwdListReq) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{5}
}

func (x *GetPwdListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetPwdListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPwdListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data []*PWD `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetPwdListResp) Reset() {
	*x = GetPwdListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPwdListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPwdListResp) ProtoMessage() {}

func (x *GetPwdListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPwdListResp.ProtoReflect.Descriptor instead.
func (*GetPwdListResp) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{6}
}

func (x *GetPwdListResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetPwdListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPwdListResp) GetData() []*PWD {
	if x != nil {
		return x.Data
	}
	return nil
}

type DelPwdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID []int64 `protobuf:"varint,1,rep,packed,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DelPwdReq) Reset() {
	*x = DelPwdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPwdReq) ProtoMessage() {}

func (x *DelPwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPwdReq.ProtoReflect.Descriptor instead.
func (*DelPwdReq) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{7}
}

func (x *DelPwdReq) GetID() []int64 {
	if x != nil {
		return x.ID
	}
	return nil
}

type DelPwdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *DelPwdResp) Reset() {
	*x = DelPwdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pwd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPwdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPwdResp) ProtoMessage() {}

func (x *DelPwdResp) ProtoReflect() protoreflect.Message {
	mi := &file_pwd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPwdResp.ProtoReflect.Descriptor instead.
func (*DelPwdResp) Descriptor() ([]byte, []int) {
	return file_pwd_proto_rawDescGZIP(), []int{8}
}

func (x *DelPwdResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DelPwdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pwd_proto protoreflect.FileDescriptor

var file_pwd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x77, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x77, 0x64,
	0x22, 0x7f, 0x0a, 0x03, 0x50, 0x57, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x22, 0x78, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x50, 0x77, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x35, 0x0a, 0x0d, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0x78, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x50, 0x77, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x35, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x77, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x54, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x50, 0x77, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x77, 0x64, 0x2e, 0x50, 0x57, 0x44, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x1b, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x50, 0x77, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x32, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x32, 0xcf, 0x01, 0x0a, 0x03, 0x50, 0x77, 0x64, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x77, 0x64, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x77, 0x64, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x77, 0x64,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x70, 0x77, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x77, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x12, 0x2e, 0x70, 0x77, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x77, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x77, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x77, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x50,
	0x77, 0x64, 0x12, 0x0e, 0x2e, 0x70, 0x77, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x77, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x77, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x77, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x77, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pwd_proto_rawDescOnce sync.Once
	file_pwd_proto_rawDescData = file_pwd_proto_rawDesc
)

func file_pwd_proto_rawDescGZIP() []byte {
	file_pwd_proto_rawDescOnce.Do(func() {
		file_pwd_proto_rawDescData = protoimpl.X.CompressGZIP(file_pwd_proto_rawDescData)
	})
	return file_pwd_proto_rawDescData
}

var file_pwd_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pwd_proto_goTypes = []any{
	(*PWD)(nil),            // 0: pwd.PWD
	(*CreatePwdReq)(nil),   // 1: pwd.CreatePwdReq
	(*CreatePwdResp)(nil),  // 2: pwd.CreatePwdResp
	(*UpdatePwdReq)(nil),   // 3: pwd.UpdatePwdReq
	(*UpdatePwdResp)(nil),  // 4: pwd.UpdatePwdResp
	(*GetPwdListReq)(nil),  // 5: pwd.GetPwdListReq
	(*GetPwdListResp)(nil), // 6: pwd.GetPwdListResp
	(*DelPwdReq)(nil),      // 7: pwd.DelPwdReq
	(*DelPwdResp)(nil),     // 8: pwd.DelPwdResp
}
var file_pwd_proto_depIdxs = []int32{
	0, // 0: pwd.GetPwdListResp.Data:type_name -> pwd.PWD
	1, // 1: pwd.Pwd.CreatePwd:input_type -> pwd.CreatePwdReq
	3, // 2: pwd.Pwd.UpdatePwd:input_type -> pwd.UpdatePwdReq
	5, // 3: pwd.Pwd.GetPwdList:input_type -> pwd.GetPwdListReq
	7, // 4: pwd.Pwd.DelPwd:input_type -> pwd.DelPwdReq
	2, // 5: pwd.Pwd.CreatePwd:output_type -> pwd.CreatePwdResp
	4, // 6: pwd.Pwd.UpdatePwd:output_type -> pwd.UpdatePwdResp
	6, // 7: pwd.Pwd.GetPwdList:output_type -> pwd.GetPwdListResp
	8, // 8: pwd.Pwd.DelPwd:output_type -> pwd.DelPwdResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pwd_proto_init() }
func file_pwd_proto_init() {
	if File_pwd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pwd_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PWD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePwdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePwdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePwdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePwdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetPwdListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetPwdListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DelPwdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pwd_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DelPwdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pwd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pwd_proto_goTypes,
		DependencyIndexes: file_pwd_proto_depIdxs,
		MessageInfos:      file_pwd_proto_msgTypes,
	}.Build()
	File_pwd_proto = out.File
	file_pwd_proto_rawDesc = nil
	file_pwd_proto_goTypes = nil
	file_pwd_proto_depIdxs = nil
}
