// Code generated by goctl. DO NOT EDIT.
// Source: pwd.proto

package pwdclient

import (
	"context"

	"go-zero-pwd/app/pwd/rpc/pwd"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePwdReq   = pwd.CreatePwdReq
	CreatePwdResp  = pwd.CreatePwdResp
	DelPwdReq      = pwd.DelPwdReq
	DelPwdResp     = pwd.DelPwdResp
	GetPwdListReq  = pwd.GetPwdListReq
	GetPwdListResp = pwd.GetPwdListResp
	PWD            = pwd.PWD
	UpdatePwdReq   = pwd.UpdatePwdReq
	UpdatePwdResp  = pwd.UpdatePwdResp

	Pwd interface {
		CreatePwd(ctx context.Context, in *CreatePwdReq, opts ...grpc.CallOption) (*CreatePwdResp, error)
		UpdatePwd(ctx context.Context, in *UpdatePwdReq, opts ...grpc.CallOption) (*UpdatePwdResp, error)
		GetPwdList(ctx context.Context, in *GetPwdListReq, opts ...grpc.CallOption) (*GetPwdListResp, error)
		DelPwd(ctx context.Context, in *DelPwdReq, opts ...grpc.CallOption) (*DelPwdResp, error)
	}

	defaultPwd struct {
		cli zrpc.Client
	}
)

func NewPwd(cli zrpc.Client) Pwd {
	return &defaultPwd{
		cli: cli,
	}
}

func (m *defaultPwd) CreatePwd(ctx context.Context, in *CreatePwdReq, opts ...grpc.CallOption) (*CreatePwdResp, error) {
	client := pwd.NewPwdClient(m.cli.Conn())
	return client.CreatePwd(ctx, in, opts...)
}

func (m *defaultPwd) UpdatePwd(ctx context.Context, in *UpdatePwdReq, opts ...grpc.CallOption) (*UpdatePwdResp, error) {
	client := pwd.NewPwdClient(m.cli.Conn())
	return client.UpdatePwd(ctx, in, opts...)
}

func (m *defaultPwd) GetPwdList(ctx context.Context, in *GetPwdListReq, opts ...grpc.CallOption) (*GetPwdListResp, error) {
	client := pwd.NewPwdClient(m.cli.Conn())
	return client.GetPwdList(ctx, in, opts...)
}

func (m *defaultPwd) DelPwd(ctx context.Context, in *DelPwdReq, opts ...grpc.CallOption) (*DelPwdResp, error) {
	client := pwd.NewPwdClient(m.cli.Conn())
	return client.DelPwd(ctx, in, opts...)
}
